run:
  timeout: 5m
  tests: true
  go: '1.22'

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Additional linters
    - gofmt
    - goimports
    - misspell
    - revive
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - makezero
    - nilerr
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0