name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🐛

        Before submitting, please check if a similar issue already exists.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a step-by-step guide to reproduce the issue.
      placeholder: |
        1. Initialize NLP with model 'en_core_web_sm'
        2. Call nlp.Tokenize("example text")
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      description: Provide a minimal code example that reproduces the issue.
      render: go
      placeholder: |
        package main

        import (
            "fmt"
            "github.com/am-sokolov/go-spacy"
        )

        func main() {
            nlp, err := spacy.NewNLP("en_core_web_sm")
            if err != nil {
                panic(err)
            }
            defer nlp.Close()

            // Your code that reproduces the bug
        }

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Ubuntu 22.04
        - Ubuntu 20.04
        - Ubuntu 18.04
        - macOS 13 (Ventura)
        - macOS 12 (Monterey)
        - macOS 11 (Big Sur)
        - Windows 11
        - Windows 10
        - Other Linux distribution
        - Other
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using?
      placeholder: "e.g., go1.21.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "e.g., 3.9.7"
    validations:
      required: true

  - type: input
    id: spacy-version
    attributes:
      label: Spacy Version
      description: What version of Spacy is installed?
      placeholder: "e.g., 3.4.4"
    validations:
      required: true

  - type: input
    id: model-name
    attributes:
      label: Spacy Model
      description: Which Spacy model are you using?
      placeholder: "e.g., en_core_web_sm"
    validations:
      required: true

  - type: input
    id: go-spacy-version
    attributes:
      label: Go-Spacy Version
      description: What version of go-spacy are you using?
      placeholder: "e.g., v1.0.0, main branch, commit hash"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please provide any relevant error messages or logs.
      render: text
      placeholder: Paste error messages here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: |
        - Build environment details
        - System architecture (amd64, arm64)
        - CGO environment variables
        - Any other relevant information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting your bug report.
      options:
        - label: I have searched existing issues for similar problems
          required: true
        - label: I have provided a minimal code example that reproduces the issue
          required: true
        - label: I have included all relevant system and version information
          required: true
        - label: I have checked the documentation and troubleshooting guide
          required: false